### ISSUE TITLE
Testing of components using storybook

### ISSUE THREAD

**Issue by mfsbo** [ckpack/v-ui-template#1]
Will it be possible to add storybook to launch a test site with component stories and test pages to show/test use cases from components build in this library.

**Comment by ckvv** [comment]
@mfsbo 
Thanks for the suggestion, `storybook` is too heavy for this progect, I extended the `markdown` syntax to add example demos, similar to `quasar` or `element`

Below is an example

```md
<<< @/demo/button/base.vue
--demo This is a button
```
<img width="564" alt="截屏2022-04-11 17 44 18" src="https://user-images.githubusercontent.com/30174970/162712279-452dd6e1-a14f-4215-bb4e-adfaab9aab25.png">

https://ckpack.github.io/v-ui-template/en/guide/compoents/button.html
